"use client";

// Auto-generated by scripts/generate.ts — source: tabler-filled
// DO NOT edit this file. To modify the animation, edit scripts/animations/circle-letter-m.ts
// then re-run: pnpm generate --icon circle-letter-m

import { motion, useAnimation } from "motion/react";
import type { Variants } from "motion/react";
import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef } from "react";
import type { LiveIconProps, LiveIconHandle } from "../../types";
import { resolveSpeed } from "@liveicons/core";

// Animation variants — defined in scripts/animations/circle-letter-m.ts
const SVG_VARIANTS: Variants = {
  normal: {},
  animate: {
    scale: [
      1,
      1.1,
      1
    ]
  }
};

const CircleLetterMIcon = forwardRef<LiveIconHandle, LiveIconProps>(
  (
    {
      animate = "on-hover",
      speed = "normal",
      size = 24,
      color = "currentColor",
      strokeWidth = 2, // unused for fill-based icons
      className,
      onMouseEnter,
      onMouseLeave,
      onClick,
      ...props
    },
    ref
  ) => {
    const controls = useAnimation();
    const isControlledRef = useRef(false);
    const duration = resolveSpeed(speed); // applied to transition below

    useEffect(() => {
      if (animate === "loop" || animate === "once") {
        controls.start("animate");
      }
    }, [animate, controls]);

    useImperativeHandle(ref, () => {
      isControlledRef.current = true;
      return {
        startAnimation: () => controls.start("animate"),
        stopAnimation: () => controls.start("normal"),
      };
    });

    const handleMouseEnter = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("animate");
        }
        onMouseEnter?.(e);
      },
      [controls, animate, onMouseEnter]
    );

    const handleMouseLeave = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("normal");
        }
        onMouseLeave?.(e);
      },
      [controls, animate, onMouseLeave]
    );

    const handleClick = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-click") {
          controls.start("animate");
        }
        onClick?.(e);
      },
      [controls, animate, onClick]
    );

    return (
      <div
        className={className}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onClick={handleClick}
        {...props}
      >
        <motion.svg
          animate={controls}
          xmlns="http://www.w3.org/2000/svg"
          width={size}
          height={size}
          viewBox="0 0 24 24"
          fill={color}
          transition={{
            ...{
  type: "spring",
  stiffness: 300,
  damping: 20,
  mass: 0.8
},
            duration,
            ...(animate === "loop" ? { repeat: Infinity, repeatType: "loop" as const } : {}),
          }}
          variants={SVG_VARIANTS}
        >
          <path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10 -10 10s-10 -4.477 -10 -10s4.477 -10 10 -10m4 6c0 -1.014 -1.336 -1.384 -1.857 -.514l-2.143 3.57l-2.143 -3.57c-.521 -.87 -1.857 -.5 -1.857 .514v8a1 1 0 0 0 1 1l.117 -.007a1 1 0 0 0 .883 -.993v-4.39l1.143 1.904l.074 .108a1 1 0 0 0 1.64 -.108l1.143 -1.904v4.39a1 1 0 0 0 2 0z" />
        </motion.svg>
      </div>
    );
  }
);

CircleLetterMIcon.displayName = "CircleLetterMIcon";

export { CircleLetterMIcon };
export type { LiveIconHandle as CircleLetterMIconHandle };
