"use client";

// Auto-generated by scripts/generate.ts — source: heroicons
// DO NOT edit this file. To modify the animation, edit scripts/animations/currency-bangladeshi.ts
// then re-run: pnpm generate --icon currency-bangladeshi

import { motion, useAnimation } from "motion/react";
import type { Variants } from "motion/react";
import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef } from "react";
import type { LiveIconProps, LiveIconHandle } from "../../types";
import { resolveSpeed } from "@liveicons/core";

// Animation variants — defined in scripts/animations/currency-bangladeshi.ts
const SVG_VARIANTS: Variants = {
  normal: {},
  animate: {
    scale: [
      1,
      1.05,
      1
    ]
  }
};

const CurrencyBangladeshiIcon = forwardRef<LiveIconHandle, LiveIconProps>(
  (
    {
      animate = "on-hover",
      speed = "normal",
      size = 24,
      color = "currentColor",
      strokeWidth = 2,
      className,
      onMouseEnter,
      onMouseLeave,
      onClick,
      ...props
    },
    ref
  ) => {
    const controls = useAnimation();
    const isControlledRef = useRef(false);
    const duration = resolveSpeed(speed); // applied to transition below

    useEffect(() => {
      if (animate === "loop" || animate === "once") {
        controls.start("animate");
      }
    }, [animate, controls]);

    useImperativeHandle(ref, () => {
      isControlledRef.current = true;
      return {
        startAnimation: () => controls.start("animate"),
        stopAnimation: () => controls.start("normal"),
      };
    });

    const handleMouseEnter = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("animate");
        }
        onMouseEnter?.(e);
      },
      [controls, animate, onMouseEnter]
    );

    const handleMouseLeave = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("normal");
        }
        onMouseLeave?.(e);
      },
      [controls, animate, onMouseLeave]
    );

    const handleClick = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-click") {
          controls.start("animate");
        }
        onClick?.(e);
      },
      [controls, animate, onClick]
    );

    return (
      <div
        className={className}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onClick={handleClick}
        {...props}
      >
        <motion.svg
          animate={controls}
          xmlns="http://www.w3.org/2000/svg"
          width={size}
          height={size}
          viewBox="0 0 24 24"
          fill="none"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
          transition={{
            ...{
  duration: 0.4
},
            duration,
            ...(animate === "loop" ? { repeat: Infinity, repeatType: "loop" as const } : {}),
          }}
          variants={SVG_VARIANTS}
        >
          <path d="M8.25 7.49997L8.66459 7.29267C9.16327 7.04333 9.75 7.40596 9.75 7.96349V10.5M9.75 10.5H15.75M9.75 10.5H8.25M9.75 10.5V15.9383C9.75 16.2921 9.91144 16.6351 10.2229 16.803C10.7518 17.0882 11.357 17.25 12 17.25C13.8142 17.25 15.3275 15.9617 15.675 14.25C15.7579 13.8414 15.412 13.5 14.995 13.5H14.25M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z"/>
        </motion.svg>
      </div>
    );
  }
);

CurrencyBangladeshiIcon.displayName = "CurrencyBangladeshiIcon";

export { CurrencyBangladeshiIcon };
export type { LiveIconHandle as CurrencyBangladeshiIconHandle };
