"use client";

// Auto-generated by scripts/generate.ts — source: heroicons
// DO NOT edit this file. To modify the animation, edit scripts/animations/user-plus.ts
// then re-run: pnpm generate --icon user-plus

import { motion, useAnimation } from "motion/react";
import type { Variants } from "motion/react";
import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef } from "react";
import type { LiveIconProps, LiveIconHandle } from "../../types";
import { resolveSpeed } from "@liveicons/core";

// Animation variants — defined in scripts/animations/user-plus.ts
const SVG_VARIANTS: Variants = {
  normal: {
    y: 0
  },
  animate: {
    y: [
      0,
      -3,
      0
    ]
  }
};

const UserPlusIcon = forwardRef<LiveIconHandle, LiveIconProps>(
  (
    {
      animate = "on-hover",
      speed = "normal",
      size = 24,
      color = "currentColor",
      strokeWidth = 2,
      className,
      onMouseEnter,
      onMouseLeave,
      onClick,
      ...props
    },
    ref
  ) => {
    const controls = useAnimation();
    const isControlledRef = useRef(false);
    const duration = resolveSpeed(speed); // applied to transition below

    useEffect(() => {
      if (animate === "loop" || animate === "once") {
        controls.start("animate");
      }
    }, [animate, controls]);

    useImperativeHandle(ref, () => {
      isControlledRef.current = true;
      return {
        startAnimation: () => controls.start("animate"),
        stopAnimation: () => controls.start("normal"),
      };
    });

    const handleMouseEnter = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("animate");
        }
        onMouseEnter?.(e);
      },
      [controls, animate, onMouseEnter]
    );

    const handleMouseLeave = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("normal");
        }
        onMouseLeave?.(e);
      },
      [controls, animate, onMouseLeave]
    );

    const handleClick = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-click") {
          controls.start("animate");
        }
        onClick?.(e);
      },
      [controls, animate, onClick]
    );

    return (
      <div
        className={className}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onClick={handleClick}
        {...props}
      >
        <motion.svg
          animate={controls}
          xmlns="http://www.w3.org/2000/svg"
          width={size}
          height={size}
          viewBox="0 0 24 24"
          fill="none"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
          transition={{
            ...{
  type: "spring",
  stiffness: 300,
  damping: 15
},
            duration,
            ...(animate === "loop" ? { repeat: Infinity, repeatType: "loop" as const } : {}),
          }}
          variants={SVG_VARIANTS}
        >
          <path d="M18 7.5V10.5M18 10.5V13.5M18 10.5H21M18 10.5H15M12.75 6.375C12.75 8.23896 11.239 9.75 9.375 9.75C7.51104 9.75 6 8.23896 6 6.375C6 4.51104 7.51104 3 9.375 3C11.239 3 12.75 4.51104 12.75 6.375ZM3.00092 19.2343C3.00031 19.198 3 19.1615 3 19.125C3 15.6042 5.85418 12.75 9.375 12.75C12.8958 12.75 15.75 15.6042 15.75 19.125V19.1276C15.75 19.1632 15.7497 19.1988 15.7491 19.2343C13.8874 20.3552 11.7065 21 9.375 21C7.04353 21 4.86264 20.3552 3.00092 19.2343Z"/>
        </motion.svg>
      </div>
    );
  }
);

UserPlusIcon.displayName = "UserPlusIcon";

export { UserPlusIcon };
export type { LiveIconHandle as UserPlusIconHandle };
