"use client";

// Auto-generated by scripts/generate.ts — source: tabler
// DO NOT edit this file. To modify the animation, edit scripts/animations/fingerprint-scan.ts
// then re-run: pnpm generate --icon fingerprint-scan

import { motion, useAnimation } from "motion/react";
import type { Variants } from "motion/react";
import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef } from "react";
import type { LiveIconProps, LiveIconHandle } from "../../types";
import { resolveSpeed } from "@liveicons/core";

// Animation variants — defined in scripts/animations/fingerprint-scan.ts
const SVG_VARIANTS: Variants = {
  normal: {
    scale: 1,
    opacity: 1
  },
  animate: {
    scale: [
      1,
      1.15,
      1
    ],
    opacity: [
      1,
      0.7,
      1
    ]
  }
};

const FingerprintScanIcon = forwardRef<LiveIconHandle, LiveIconProps>(
  (
    {
      animate = "on-hover",
      speed = "normal",
      size,
      color = "currentColor",
      strokeWidth = 2,
      className,
      onMouseEnter,
      onMouseLeave,
      onClick,
      ...props
    },
    ref
  ) => {
    const controls = useAnimation();
    const isControlledRef = useRef(false);
    const duration = resolveSpeed(speed); // applied to transition below

    useEffect(() => {
      if (animate === "loop" || animate === "once") {
        controls.start("animate");
      }
    }, [animate, controls]);

    useImperativeHandle(ref, () => {
      isControlledRef.current = true;
      return {
        startAnimation: () => controls.start("animate"),
        stopAnimation: () => controls.start("normal"),
      };
    });

    const handleMouseEnter = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("animate");
        }
        onMouseEnter?.(e);
      },
      [controls, animate, onMouseEnter]
    );

    const handleMouseLeave = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("normal");
        }
        onMouseLeave?.(e);
      },
      [controls, animate, onMouseLeave]
    );

    const handleClick = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-click") {
          controls.start("animate");
        }
        onClick?.(e);
      },
      [controls, animate, onClick]
    );

    return (
      <div
        className={className}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onClick={handleClick}
        {...props}
      >
        <motion.svg
          animate={controls}
          xmlns="http://www.w3.org/2000/svg"
          width={size ?? "100%"}
          height={size ?? "100%"}
          viewBox="0 0 24 24"
          fill="none"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
          transition={{
            ...{
  duration: 0.6,
  ease: "easeInOut"
},
            duration,
            ...(animate === "loop" ? { repeat: Infinity, repeatType: "loop" as const } : {}),
          }}
          variants={SVG_VARIANTS}
        >
          <path d="M9 11a3 3 0 0 1 6 0c0 1.657 .612 3.082 1 4" />
  <path d="M12 11v1.75c-.001 1.11 .661 2.206 1 3.25" />
  <path d="M9 14.25c.068 .58 .358 1.186 .5 1.75" />
  <path d="M4 8v-2a2 2 0 0 1 2 -2h2" />
  <path d="M4 16v2a2 2 0 0 0 2 2h2" />
  <path d="M16 4h2a2 2 0 0 1 2 2v2" />
  <path d="M16 20h2a2 2 0 0 0 2 -2v-2" />
        </motion.svg>
      </div>
    );
  }
);

FingerprintScanIcon.displayName = "FingerprintScanIcon";

export { FingerprintScanIcon };
export type { LiveIconHandle as FingerprintScanIconHandle };
