"use client";

// Auto-generated by scripts/generate.ts — source: tabler
// DO NOT edit this file. To modify the animation, edit scripts/animations/ripple-down.ts
// then re-run: pnpm generate --icon ripple-down

import { motion, useAnimation } from "motion/react";
import type { Variants } from "motion/react";
import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef } from "react";
import type { LiveIconProps, LiveIconHandle } from "../../types";
import { resolveSpeed } from "@liveicons/core";

// Animation variants — defined in scripts/animations/ripple-down.ts
const SVG_VARIANTS: Variants = {
  normal: {
    y: 0
  },
  animate: {
    y: [
      0,
      4,
      0
    ]
  }
};

const RippleDownIcon = forwardRef<LiveIconHandle, LiveIconProps>(
  (
    {
      animate = "on-hover",
      speed = "normal",
      size = 24,
      color = "currentColor",
      strokeWidth = 2,
      className,
      onMouseEnter,
      onMouseLeave,
      onClick,
      ...props
    },
    ref
  ) => {
    const controls = useAnimation();
    const isControlledRef = useRef(false);
    const duration = resolveSpeed(speed); // applied to transition below

    useEffect(() => {
      if (animate === "loop" || animate === "once") {
        controls.start("animate");
      }
    }, [animate, controls]);

    useImperativeHandle(ref, () => {
      isControlledRef.current = true;
      return {
        startAnimation: () => controls.start("animate"),
        stopAnimation: () => controls.start("normal"),
      };
    });

    const handleMouseEnter = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("animate");
        }
        onMouseEnter?.(e);
      },
      [controls, animate, onMouseEnter]
    );

    const handleMouseLeave = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-hover") {
          controls.start("normal");
        }
        onMouseLeave?.(e);
      },
      [controls, animate, onMouseLeave]
    );

    const handleClick = useCallback(
      (e: React.MouseEvent<HTMLDivElement>) => {
        if (!isControlledRef.current && animate === "on-click") {
          controls.start("animate");
        }
        onClick?.(e);
      },
      [controls, animate, onClick]
    );

    return (
      <div
        className={className}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        onClick={handleClick}
        {...props}
      >
        <motion.svg
          animate={controls}
          xmlns="http://www.w3.org/2000/svg"
          width={size}
          height={size}
          viewBox="0 0 24 24"
          fill="none"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
          transition={{
            ...{
  type: "spring",
  stiffness: 400,
  damping: 15,
  mass: 0.5
},
            duration,
            ...(animate === "loop" ? { repeat: Infinity, repeatType: "loop" as const } : {}),
          }}
          variants={SVG_VARIANTS}
        >
          <path d="M3 7q 4.5 -3 9 0t 9 0" />
  <path d="M3 17q 4.5 -3 9 0q .213 .142 .427 .27" />
  <path d="M3 12q 4.5 -3 9 0q 2.006 1.338 4.012 1.482" />
  <path d="M19 16v6" />
  <path d="M22 19l-3 3l-3 -3" />
        </motion.svg>
      </div>
    );
  }
);

RippleDownIcon.displayName = "RippleDownIcon";

export { RippleDownIcon };
export type { LiveIconHandle as RippleDownIconHandle };
